### ISSUE TITLE
[Bug]: CreateNotificationSuccessResponse Error

### ISSUE THREAD

**Issue by kalaomer** [OneSignal/onesignal-python-api#8]
### What happened?

Hello,

I want to use this library to create notifications for my Django project. And I did it well but because of the bug, my code is raised an error. The main reason is parsing create notification's response I guess.

### Steps to reproduce?

```Markdown
configuration = onesignal.Configuration(
        app_key=ONESIGNAL_APP_KEY,
    )

    with onesignal.ApiClient(configuration) as api_client:
        # Create an instance of the API class
        api_instance = default_api.DefaultApi(api_client)

        player = Player(
            app_id=ONESIGNAL_APP_ID,
            device_type=11,
            external_user_id="CUSTOM_USER_ID",
            identifier="SOME_EMAIL",
        )

        notification = Notification(
            app_id=ONESIGNAL_APP_ID,
            include_external_user_ids=["CUSTOM_USER_ID"],
            template_id="MY_TEMPLATE_ID"
        )

        try:
            # Add a device
            api_instance.create_player(player)
        except onesignal.ApiException as e:
            print("Exception when calling DefaultApi->create_player: %s\n" % e)

        try:
            api_instance.create_notification(notification)
        except onesignal.ApiException as e:
            print("Exception when calling DefaultApi->create_notification: %s\n" % e)
```
```


### What did you expect to happen?

I expect that `api_instance.create_notification(notification)` function did not raise for response creation error.

### Relevant log output

```Shell
Here is the error log


Traceback (most recent call last):
  File "/app/apps/customers/models.py", line 64, in create_onesignal_player
    api_instance.create_notification(notification)
  File "/usr/local/lib/python3.10/site-packages/onesignal/api/default_api.py", line 1423, in create_notification
    return self.create_notification_endpoint.call_with_http_info(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/onesignal/api_client.py", line 881, in call_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.10/site-packages/onesignal/api_client.py", line 423, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.10/site-packages/onesignal/api_client.py", line 228, in __call_api
    return_data = self.deserialize(
  File "/usr/local/lib/python3.10/site-packages/onesignal/api_client.py", line 334, in deserialize
    deserialized_data = validate_and_convert_types(
  File "/usr/local/lib/python3.10/site-packages/onesignal/model_utils.py", line 1583, in validate_and_convert_types
    converted_instance = attempt_convert_item(
  File "/usr/local/lib/python3.10/site-packages/onesignal/model_utils.py", line 1472, in attempt_convert_item
    raise conversion_exc
  File "/usr/local/lib/python3.10/site-packages/onesignal/model_utils.py", line 1463, in attempt_convert_item
    return deserialize_model(input_value, valid_class,
  File "/usr/local/lib/python3.10/site-packages/onesignal/model_utils.py", line 1377, in deserialize_model
    return model_class._new_from_openapi_data(**kw_args)
  File "/usr/local/lib/python3.10/site-packages/onesignal/model_utils.py", line 49, in wrapped_init
    return fn(_self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/onesignal/model_utils.py", line 372, in _new_from_openapi_data
    return cls._from_openapi_data(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/onesignal/model_utils.py", line 49, in wrapped_init
    return fn(_self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/onesignal/model/create_notification_success_response.py", line 196, in _from_openapi_data
    setattr(self, var_name, var_value)
  File "/usr/local/lib/python3.10/site-packages/onesignal/model_utils.py", line 190, in __setattr__
    self[attr] = value
  File "/usr/local/lib/python3.10/site-packages/onesignal/model_utils.py", line 511, in __setitem__
    self.set_attribute(name, value)
  File "/usr/local/lib/python3.10/site-packages/onesignal/model_utils.py", line 162, in set_attribute
    value = validate_and_convert_types(
  File "/usr/local/lib/python3.10/site-packages/onesignal/model_utils.py", line 1583, in validate_and_convert_types
    converted_instance = attempt_convert_item(
  File "/usr/local/lib/python3.10/site-packages/onesignal/model_utils.py", line 1458, in attempt_convert_item
    raise get_type_error(input_value, path_to_item, valid_classes,
onesignal.exceptions.ApiTypeError: Invalid type for variable 'external_id'. Required value type is str and passed type was NoneType at ['received_data']['external_id']
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kesheshyan** [comment]
Hey @kalaomer , thanks for reporting. I believe we should have fixed this issue in one of the recent updates. Please feel free to reopen if this issue persists.
